const products = [
  { id: 1, name: "Gold Earrings", price: 5000, image: "/images/ear1.jpg", description: "Beautiful handcrafted gold earrings perfect for special occasions." },
  { id: 2, name: "Elegant Necklace", price: 15499, image: "/images/eleneck.jpg", description: "A stunning necklace that adds elegance to your style." },
  { id: 3, name: "Diamond rings", price: 2299, image: "/images/ring.jpg", description: "Sparkling diamond ring to celebrate love and elegance." },
  { id: 4, name: "Gold Earrings", price: 5950, image: "/images/ear2.jpg", description: "Beautiful handcrafted gold earrings perfect for special occasions." },
  { id: 5, name: "Elegant Necklace", price: 15400, image: "/images/eleneck1.jpg", description: "A stunning necklace that adds elegance to your style." },
  { id: 6, name: "Diamond rings", price: 2240, image: "/images/ring2.jpg", description: "Sparkling diamond ring to celebrate love and elegance." },
  { id: 7, name: "Gold Earrings", price: 5900, image: "/images/ear3.jpg", description: "Beautiful handcrafted gold earrings perfect for special occasions." },
  { id: 8, name: "Elegant Necklace", price: 1680, image: "/images/eleneck2.jpg", description: "A stunning necklace that adds elegance to your style." },
  { id: 9, name: "Diamond rings", price: 2990, image: "/images/ring3.jpg", description: "Sparkling diamond ring to celebrate love and elegance." },
  { id: 10, name: "Gold Earrings", price: 5988, image: "/images/ear4.jpg", description: "Beautiful handcrafted gold earrings perfect for special occasions." },
  { id: 11, name: "Elegant Necklace", price: 2500, image: "/images/eleneck3.jpg", description: "A stunning necklace that adds elegance to your style." },
  { id: 12, name: "Diamond rings", price: 3000, image: "/images/ring4.jpg", description: "Sparkling diamond ring to celebrate love and elegance." },
  { id: 13, name: "Gold Earrings", price: 5889, image: "/images/ear5.jpg",description: "Beautiful handcrafted gold earrings perfect for special occasions." },
  { id: 14, name: "Elegant Necklace", price: 15499, image: "/images/eleneck4.jpg",description: "A stunning necklace that adds elegance to your style." },
  { id: 15, name: "Diamond rings", price: 2299, image: "/images/ring5.jpg",description: "Sparkling diamond ring to celebrate love and elegance."  },
  { id: 16, name: "Gold Earrings", price: 5999, image: "/images/ear6.jpg",description: "Beautiful handcrafted gold earrings perfect for special occasions." },
  { id: 17, name: "Elegant Necklace", price: 15499, image: "/images/eleneck5.jpg",description: "A stunning necklace that adds elegance to your style." },
  { id: 18, name: "Diamond rings", price: 4409, image: "/images/ring6.jpg",description: "Sparkling diamond ring to celebrate love and elegance."  },
  { id: 19, name: "Gold Earrings", price: 5999, image: "/images/ear7.jpg",description: "Beautiful handcrafted gold earrings perfect for special occasions." },
  { id: 20, name: "Elegant Necklace", price: 15499, image: "/images/eleneck6.jpg",description: "A stunning necklace that adds elegance to your style." },
  { id: 21, name: "Diamond rings", price: 2299, image: "/images/ring7.jpg",description: "Sparkling diamond ring to celebrate love and elegance."  },
  { id: 22, name: "Gold Earrings", price: 5999, image: "/images/ear8.jpg",description: "Beautiful handcrafted gold earrings perfect for special occasions." },
  { id: 23, name: "Elegant Necklace", price: 15499, image: "/images/eleneck8.jpg",description: "A stunning necklace that adds elegance to your style." },
  { id: 24, name: "Diamond rings", price: 2290, image: "/images/ring8.jpg",description: "Sparkling diamond ring to celebrate love and elegance."  },
  { id: 25, name: "Gold Earrings", price: 5999, image: "/images/ear9.jpg",description: "Beautiful handcrafted gold earrings perfect for special occasions." },
  { id: 26, name: "Elegant Necklace", price: 15643, image: "/images/eleneck9.jpg",description: "A stunning necklace that adds elegance to your style." },
  { id: 27, name: "Diamond rings", price: 2221, image: "/images/ring9.jpg",description: "Sparkling diamond ring to celebrate love and elegance."  },
  { id: 28, name: "Gold Earrings", price: 5480, image: "/images/ear10.jpg",description: "Beautiful handcrafted gold earrings perfect for special occasions." },
  { id: 29, name: "Elegant Necklace", price: 15498, image: "/images/eleneck10.jpg",description: "A stunning necklace that adds elegance to your style." },
  { id: 30, name: "Diamond rings", price: 3300, image: "/images/ring10.jpg",description: "Sparkling diamond ring to celebrate love and elegance."  },
];
export default products;