const products = [
  { id: 1, name: "Gold Earrings", price: 5999, image: "/images/ear1.jpg" },
  { id: 2, name: "Elegant Necklace", price: 15499, image: "/images/eleneck.jpg" },
  { id: 3, name: "Diamond rings", price: 2299, image: "/images/ring.jpg" },
  { id: 4, name: "Gold Earrings", price: 5999, image: "/images/ear2.jpg" },
  { id: 5, name: "Elegant Necklace", price: 15499, image: "/images/eleneck1.jpg" },
  { id: 6, name: "Diamond rings", price: 2299, image: "/images/ring2.jpg" },
  { id: 7, name: "Gold Earrings", price: 5999, image: "/images/ear3.jpg" },
  { id: 8, name: "Elegant Necklace", price: 15499, image: "/images/eleneck2.jpg" },
  { id: 9, name: "Diamond rings", price: 2299, image: "/images/ring3.jpg" },
  { id: 10, name: "Gold Earrings", price: 5999, image: "/images/ear4.jpg" },
  { id: 11, name: "Elegant Necklace", price: 15499, image: "/images/eleneck3.jpg" },
  { id: 12, name: "Diamond rings", price: 2299, image: "/images/ring4.jpg" },
  { id: 13, name: "Gold Earrings", price: 5999, image: "/images/ear5.jpg" },
  { id: 14, name: "Elegant Necklace", price: 15499, image: "/images/eleneck4.jpg" },
  { id: 15, name: "Diamond rings", price: 2299, image: "/images/ring5.jpg" },
  { id: 16, name: "Gold Earrings", price: 5999, image: "/images/ear6.jpg" },
  { id: 17, name: "Elegant Necklace", price: 15499, image: "/images/eleneck5.jpg" },
  { id: 18, name: "Diamond rings", price: 2299, image: "/images/ring6.jpg" },
  { id: 19, name: "Gold Earrings", price: 5999, image: "/images/ear7.jpg" },
  { id: 20, name: "Elegant Necklace", price: 15499, image: "/images/eleneck6.jpg" },
  { id: 21, name: "Diamond rings", price: 2299, image: "/images/ring7.jpg" },
  { id: 22, name: "Gold Earrings", price: 5999, image: "/images/ear8.jpg" },
  { id: 23, name: "Elegant Necklace", price: 15499, image: "/images/eleneck8.jpg" },
  { id: 24, name: "Diamond rings", price: 2299, image: "/images/ring8.jpg" },
  { id: 25, name: "Gold Earrings", price: 5999, image: "/images/ear9.jpg" },
  { id: 26, name: "Elegant Necklace", price: 15499, image: "/images/eleneck9.jpg" },
  { id: 27, name: "Diamond rings", price: 2299, image: "/images/ring9.jpg" },
  { id: 28, name: "Gold Earrings", price: 5999, image: "/images/ear10.jpg" },
  { id: 29, name: "Elegant Necklace", price: 15499, image: "/images/eleneck10.jpg" },
  { id: 30, name: "Diamond rings", price: 2299, image: "/images/ring10.jpg" },
];
export default products;
